name: CI
on: [push]
jobs:
  vet:
    name: Vet source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dev dependencies
        run: bun install --development

      - name: Typecheck code
        run: bun run build

      - name: Lint code
        run: bun run lint

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Login to Docker registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry:
      #     username:
      #     password:
      #
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        # push: true
        # tags:
        # cache-from:
        # cache-to: type=inline
